### ISSUE TITLE
Utility Function for Vector Similarity Search

### ISSUE THREAD

**Issue by devansh-shah-11** [Devasy23/FaceRec#18]
**Description**
We need a new utility function in [Database.py](API/database.py) that performs a vector similarity search. This function should take an embedding vector as input and return the most similar vectors from the MongoDB Atlas database using Euclidean distance as the similarity measure.

This utility function will be used by the recognise_face() endpoint to find the most similar face in the database.

**Expected Behavior**

The endpoint should take n as input from the user and return the top n most similar vectors from MongoDB Database

**Benefits**
This feature will automate the finding of top n most similar vectors to the given face to help identify the employee

**Tasks**
Explore the MongoDB vector search tutorial
Write a function to return the most similar vectors

<details open>
<summary>Checklist</summary>

- [X] Modify `API/database.py` ✓ https://github.com/devansh-shah-11/FaceRec/commit/d6366ebfcc133c30f5e069c0508a89b52686ba57 [Edit](https://github.com/devansh-shah-11/FaceRec/edit/sweep/utility_function_for_vector_similarity_s_0cb05/API/database.py#L22-L22)
- [X] Running GitHub Actions for `API/database.py` ✓  [Edit](https://github.com/devansh-shah-11/FaceRec/edit/sweep/utility_function_for_vector_similarity_s_0cb05/API/database.py#L22-L22)
- [X] Modify `API/route.py` ✓ https://github.com/devansh-shah-11/FaceRec/commit/7b8ca4e13c930240c7aef7d25b09dd19d42e82df [Edit](https://github.com/devansh-shah-11/FaceRec/edit/sweep/utility_function_for_vector_similarity_s_0cb05/API/route.py#L176-L220)
- [X] Running GitHub Actions for `API/route.py` ✓  [Edit](https://github.com/devansh-shah-11/FaceRec/edit/sweep/utility_function_for_vector_similarity_s_0cb05/API/route.py#L176-L220)
</details>
